# Generated by Django 5.1.4 on 2024-12-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telergram chat_id'),
        ),
    ]
